version: '3.9'

services:
  frontend:
    build:
      context: /home/blockscout/blockscout-frontend
    image: blockscout-frontend:local
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    ports:
      - "3000:3000"
    env_file:
      -  /home/blockscout/blockscout-frontend/.env.local
